"use server";

import OpenAI from "openai";
import { ContractAnalysisError } from "@/lib/errors";
import { splitIntoChunks } from "@/lib/text-utils";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

interface AnalysisResult {
  summary: string;
  keyTerms: string[];
  potentialRisks: string[];
  importantClauses: string[];
  recommendations?: string[];
}

interface AnalysisMetadata {
  analyzedAt: string;
  documentName: string;
  modelVersion: string;
  totalChunks?: number;
}

// Add retry logic for API failures
async function withRetry<T>(fn: () => Promise<T>, maxAttempts = 3): Promise<T> {
  let lastError: unknown;
  
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      if (attempt === maxAttempts) break;
      
      // Exponential backoff
      await new Promise((resolve) => 
        setTimeout(resolve, Math.pow(2, attempt - 1) * 1000)
      );
    }
  }
  
  throw new ContractAnalysisError(
    'Maximum retry attempts reached',
    'API_ERROR',
    lastError
  );
}

// Function to analyze a single chunk
async function analyzeChunk(
  chunk: string,
  chunkIndex: number,
  totalChunks: number
): Promise<AnalysisResult> {
  try {
    const systemPrompt = "You are a legal expert. Analyze this contract section concisely.";
    const userPrompt = `Section ${chunkIndex + 1}/${totalChunks}:\n${chunk}\n\nProvide JSON with: summary (brief), keyTerms, potentialRisks, importantClauses, recommendations.`;

    const response = await withRetry(async () => {
      return await openai.chat.completions.create({
        model: "gpt-3.5-turbo-1106",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
        max_tokens: 1000,
        response_format: { type: "json_object" },
      });
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new ContractAnalysisError(
        'No analysis generated by AI model',
        'API_ERROR'
      );
    }

    return JSON.parse(content) as AnalysisResult;
  } catch (error) {
    if (error instanceof ContractAnalysisError) {
      throw error;
    }
    throw new ContractAnalysisError(
      `Failed to analyze chunk ${chunkIndex + 1}`,
      'API_ERROR',
      error
    );
  }
}

// Function to merge multiple analysis results
function mergeAnalysisResults(results: AnalysisResult[]): AnalysisResult {
  try {
    if (!Array.isArray(results) || results.length === 0) {
      throw new ContractAnalysisError(
        'No analysis results to merge',
        'TEXT_PROCESSING_ERROR'
      );
    }

    const merged: AnalysisResult = {
      summary: "",
      keyTerms: [],
      potentialRisks: [],
      importantClauses: [],
      recommendations: [],
    };

    // Merge all arrays and remove duplicates
    results.forEach((result) => {
      if (!result || typeof result !== 'object') {
        throw new ContractAnalysisError(
          'Invalid analysis result format',
          'TEXT_PROCESSING_ERROR'
        );
      }

      if (Array.isArray(result.keyTerms)) merged.keyTerms.push(...result.keyTerms);
      if (Array.isArray(result.potentialRisks)) merged.potentialRisks.push(...result.potentialRisks);
      if (Array.isArray(result.importantClauses)) merged.importantClauses.push(...result.importantClauses);
      if (Array.isArray(result.recommendations)) merged.recommendations?.push(...result.recommendations);
    });

    // Remove duplicates using Set
    merged.keyTerms = Array.from(new Set(merged.keyTerms));
    merged.potentialRisks = Array.from(new Set(merged.potentialRisks));
    merged.importantClauses = Array.from(new Set(merged.importantClauses));
    if (merged.recommendations) {
      merged.recommendations = Array.from(new Set(merged.recommendations));
    }

    // Create a comprehensive summary
    merged.summary = `This contract analysis is based on ${results.length} sections. ` + 
      (results[0]?.summary || 'No summary available.');

    return merged;
  } catch (error) {
    if (error instanceof ContractAnalysisError) {
      throw error;
    }
    throw new ContractAnalysisError(
      'Failed to merge analysis results',
      'TEXT_PROCESSING_ERROR',
      error
    );
  }
}

export async function analyzeContract(formData: FormData) {
  try {
    if (!process.env.OPENAI_API_KEY) {
      throw new ContractAnalysisError(
        "OpenAI API key is not configured. Please contact the administrator.",
        "API_ERROR"
      );
    }

    // Get text and filename from FormData
    const text = formData.get("text");
    const filename = formData.get("filename");

    if (!text || typeof text !== 'string') {
      throw new ContractAnalysisError(
        "No text content received",
        "INVALID_INPUT"
      );
    }

    if (!filename || typeof filename !== 'string') {
      throw new ContractAnalysisError(
        "No filename received",
        "INVALID_INPUT"
      );
    }

    // Split the content into manageable chunks
    const chunks = splitIntoChunks(text);
    console.log(`Split contract into ${chunks.length} chunks`);
    
    // Analyze each chunk
    const analysisResults = await Promise.all(
      chunks.map((chunk, index) => analyzeChunk(chunk, index, chunks.length))
    );

    // Merge the results
    const mergedAnalysis = mergeAnalysisResults(analysisResults);

    // Add metadata
    return {
      ...mergedAnalysis,
      metadata: {
        analyzedAt: new Date().toISOString(),
        documentName: filename,
        modelVersion: "gpt-3.5-turbo-1106",
        totalChunks: chunks.length
      } as AnalysisMetadata,
    };
  } catch (error) {
    console.error("Error generating analysis:", error);
    throw error instanceof ContractAnalysisError
      ? error
      : new ContractAnalysisError(
          `Failed to analyze contract: ${error instanceof Error ? error.message : 'Unknown error'}`,
          'TEXT_PROCESSING_ERROR',
          error
        );
  }
}